const constants = require('./constants');

module.exports = {
    'no-cond-assign': [constants.ERROR, 'always'],
    'no-console': constants.WARNING,
    'no-constant-condition': constants.ERROR,
    'no-control-regex': constants.OFF,
    'no-debugger': constants.WARNING,
    'no-dupe-args': constants.ERROR,
    'no-dupe-keys': constants.ERROR,
    'no-duplicate-case': constants.ERROR,
    'no-empty': constants.ERROR,
    'no-empty-character-class': constants.ERROR,
    'no-ex-assign': constants.ERROR,
    'no-extra-boolean-cast': constants.ERROR,
    'no-extra-parens': [constants.OFF, 'all'],
    'no-extra-semi': constants.ERROR,
    'no-func-assign': constants.ERROR,
    'no-inner-declarations': [constants.ERROR, 'both'],
    'no-invalid-regexp': constants.ERROR,
    'no-irregular-whitespace': constants.ERROR,
    'no-negated-in-lhs': constants.ERROR,
    'no-obj-calls': constants.ERROR,
    'no-prototype-builtins': constants.ERROR,
    'no-regex-spaces': constants.ERROR,
    'no-sparse-arrays': constants.ERROR,
    'no-unexpected-multiline': constants.ERROR,
    'no-unreachable': constants.ERROR,
    'no-unsafe-finally': constants.ERROR,
    'use-isnan': constants.ERROR,
    'valid-jsdoc': constants.OFF,
    'valid-typeof': constants.ERROR
};
