const constants = require('./constants');

module.exports = {
    'array-bracket-spacing': [constants.ERROR, 'never'],
    'block-spacing': [constants.ERROR, 'always'],
    'brace-style': [constants.ERROR, '1tbs'],
    camelcase: [constants.ERROR, { properties: 'never' }],
    'comma-dangle': [constants.ERROR, 'never'],
    'comma-spacing': [constants.ERROR, { before: false, after: true }],
    'comma-style': [constants.ERROR, 'last'],
    'computed-property-spacing': [constants.ERROR, 'never'],
    'consistent-this': constants.OFF,
    'eol-last': [constants.ERROR, 'unix'],
    'func-names': constants.OFF,
    'func-style': constants.OFF,
    'id-blacklist': constants.OFF,
    'id-length': constants.OFF,
    'id-match': constants.OFF,
    indent: [constants.ERROR, constants.INDENTATION],
    'jsx-quotes': [constants.ERROR, 'prefer-double'],
    'key-spacing': [constants.ERROR, { beforeColon: false, afterColon: true }],
    'keyword-spacing': [constants.ERROR, { before: true, after: true }],
    'linebreak-style': [constants.ERROR, 'unix'],
    'lines-around-comment': constants.OFF,
    'max-depth': constants.OFF,
    'max-len': [constants.ERROR, {
        code: 80,
        ignoreComments:
        false,
        ignoreUrls: true
    }],
    'max-lines': constants.OFF,
    'max-nested-callbacks': constants.OFF,
    'max-params': constants.OFF,
    'max-statements': constants.OFF,
    'max-statements-per-line': [constants.ERROR, { max: 1 }],
    'multiline-ternary': constants.OFF,
    'new-cap': [constants.ERROR, { newIsCap: true, capIsNew: false }],
    'new-parens': constants.ERROR,
    'newline-after-var': constants.OFF,
    'newline-before-return': constants.OFF,
    'newline-per-chained-call': constants.ERROR,
    'no-array-constructor': constants.ERROR,
    'no-bitwise': constants.OFF,
    'no-continue': constants.OFF,
    'no-inline-comments': constants.OFF,
    'no-lonely-if': constants.ERROR,
    'no-mixed-operators': [constants.ERROR, { allowSamePrecedence: true }],
    'no-mixed-spaces-and-tabs': constants.ERROR,
    'no-multiple-empty-lines': [constants.ERROR, {
        max: 1,
        maxEOF: 1,
        maxBOF: 0
    }],
    'no-negated-condition': constants.ERROR,
    'no-nested-ternary': constants.ERROR,
    'no-new-object': constants.ERROR,
    'no-plusplus': constants.OFF,
    'no-restricted-syntax': constants.OFF,
    'no-spaced-func': constants.ERROR,
    'no-tabs': constants.ERROR,
    'no-ternary': constants.OFF,
    'no-trailing-spaces': constants.ERROR,
    'no-underscore-dangle': constants.ERROR,
    'no-unneeded-ternary': [constants.ERROR, { defaultAssignment: false }],
    'no-whitespace-before-property': constants.ERROR,
    'object-curly-newline': [constants.ERROR, { multiline: true }],
    'object-curly-spacing': [constants.ERROR, 'always'],
    'object-property-newline': constants.OFF,
    'one-var': [constants.ERROR, 'never'],
    'one-var-declaration-per-line': [constants.ERROR, 'always'],
    'operator-assignment': [constants.ERROR, 'always'],
    'operator-linebreak': [constants.ERROR, 'after'],
    'padded-blocks': [constants.ERROR, 'never'],
    'quote-props': [constants.ERROR, 'as-needed', { keywords: true }],
    quotes: [constants.ERROR, 'single', { allowTemplateLiterals: true }],
    'require-jsdoc': constants.OFF,
    semi: [constants.ERROR, 'always'],
    'semi-spacing': [constants.ERROR, { before: false, after: true }],
    'sort-vars': constants.OFF,
    'space-before-blocks': [constants.ERROR, 'always'],
    'space-before-function-paren': [constants.ERROR, {
        anonymous: 'always',
        named: 'never'
    }],
    'space-in-parens': [constants.ERROR, 'never'],
    'space-infix-ops': constants.ERROR,
    'space-unary-ops': [constants.ERROR, { words: true, nonwords: false }],
    'spaced-comment': [constants.ERROR, 'always'],
    'unicode-bom': [constants.ERROR, 'never'],
    'wrap-regex': constants.OFF
};
